#ifndef SCAN8051DEF_H
#define SCAN8051DEF_H
#define yyparse scan_yyparse
#define yyerror scan_yyerror
#define yylval scan_yylval
#define yychar scan_yychar
#define yynerrs scan_nerrs
#define yytext scan_yytext
#define yy_flush_buffer scan_yy_flush_buffer
#define yyin scan_yyin
#define yyget_lineno scan_yyget_lineno
#define yylineno scan_yylineno
#define yyget_in scan_yyget_in
#define yyget_out scan_yyget_out
#define yyout scan_yyout
#define yyget_leng scan_yyget_leng
#define yyleng scan_yyleng
#define yyget_text scan_yyget_text
#define yyset_lineno scan_yyset_lineno
#define yyset_in scan_yyset_in
#define yyset_out scan_yyset_out
#define yyget_debug scan_yyget_debug
#define yy_flex_debug scan_yy_flex_debug
#define yyset_debug scan_yyset_debug
#define yyalloc scan_yyalloc
#define yy_create_buffer scan_yy_create_buffer
#define yyrealloc scan_yyrealloc
#define yyrestart scan_yyrestart
#define yylex scan_yylex
#define yy_switch_to_buffer scan_yy_switch_to_buffer
#define yy_scan_buffer scan_yy_scan_buffer
#define yy_scan_bytes scan_yy_scan_bytes
#define yy_scan_string scan_yy_scan_string
#define yypush_buffer_state scan_yypush_buffer_state
#define yyfree scan_yyfree
#define yy_delete_buffer scan_yy_delete_buffer
#define yypop_buffer_state scan_yypop_buffer_state
#define yylex_destroy scan_yylex_destroy
#endif // SCAN8051DEF_H
